name: Sync From Private Repo
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to create (e.g., v1.0.0)'
        required: true
      release_name:
        description: 'Release title'
        required: false
      release_body:
        description: 'Release notes'
        required: false
permissions:
  contents: write  # :arrow_left: allows committing, pushing tags, and creating releases
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout public repo
      uses: actions/checkout@v4
    - name: Set up Git identity
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "actions@github.com"
    - name: Clone private repo
      run: |
        git clone https://x-access-token:${{ secrets.JAVA_TOKEN }}@github.com/Apisero-Connectors/asn-one-nttdata.git private-repo
    - name: Copy files from private to public
      run: |
        rsync -av --exclude='.git' private-repo/ ./
    - name: Make gradlew executable
      run: |
        chmod +x ./gradlew
    - name: Commit changes to public repo
      run: |
        git add .
        git diff --cached --quiet || git commit -m "Sync from private repo"
        git push origin main
    - name: Create tag in public repo if it doesn’t exist
      run: |
        if git ls-remote --tags origin | grep -q "refs/tags/${{ github.event.inputs.tag }}$"; then
           echo "Tag '${{ github.event.inputs.tag }}' already exists on remote. Skipping."
        else
           git tag "${{ github.event.inputs.tag }}"
           git push origin "${{ github.event.inputs.tag }}"
        fi
    - name: Create GitHub release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.event.inputs.tag }}
        name: ${{ github.event.inputs.release_name || github.event.inputs.tag }}
        body: ${{ github.event.inputs.release_body || 'Release created by GitHub Actions' }}
      env:
        GITHUB_TOKEN: ${{ secrets.JAVA_TOKEN }}